# Generated by Django 5.2.10 on 2026-01-29 04:55

import ecommerce_project.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_birth_date_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce_project.utils.avatar_path),
        ),
    ]
