# Generated by Django 5.2.10 on 2026-01-29 05:31

import django.db.models.deletion
import ecommerce_project.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce_project.utils.brand_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce_project.utils.national_id_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
