# Generated by Django 5.2.10 on 2026-01-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_brand_image_profile_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
