# Generated by Django 5.2.11 on 2026-05-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='base_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='country',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='country',
            name='stability',
            field=models.IntegerField(default=70),
        ),
    ]
