# Generated by Django 5.2.14 on 2026-05-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_age_profile_brand_intro_profile_brand_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='national_id_photo',
        ),
    ]
