# Generated by Django 5.2.11 on 2026-05-31 16:11

import ecommerce_project.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_address_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce_project.utils.avatar_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce_project.utils.avatar_path),
        ),
    ]
