# Generated by Django 5.2.14 on 2026-06-09 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_profile_cover_image_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
