# Generated by Django 5.2.11 on 2026-05-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_comments/'),
        ),
    ]
