# Generated by Django 5.2.14 on 2026-05-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon_order_discount_amount_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Currency code, e.g., USD, EGP, SAR', max_length=3, unique=True)),
                ('rate_from_usd', models.DecimalField(decimal_places=4, default=1.0, help_text='How much of this currency equals 1 USD. e.g. 50.0 for EGP', max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate_applied',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code, e.g., USD, EGP', max_length=3),
        ),
    ]
