# Generated by Django 5.2.14 on 2026-05-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_exchangerate_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
