# Generated by Django 5.2.11 on 2026-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_available_colors_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code for UI badge', max_length=20, null=True),
        ),
    ]
