# Generated by Django 5.2.14 on 2026-05-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_fabric',
        ),
    ]
