# Generated by Django 5.2.11 on 2026-05-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productimage_is_fabric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
