# Generated by Django 5.2.14 on 2026-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_review_image_review_parent_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
