# Generated by Django 5.2.14 on 2026-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_additional_images_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductDislike',
        ),
    ]
