# Generated by Django 5.2.14 on 2026-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_review_is_dislike_review_is_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_before_sale",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
