# Generated by Django 5.2.14 on 2026-06-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_product_price_before_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fabric_focus",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
