# Generated by Django 5.2.14 on 2026-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_product_fabric_focus"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="can_be_hijabi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="needs_basic",
            field=models.BooleanField(default=False),
        ),
    ]
