# Generated by Django 5.2.14 on 2026-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_product_can_be_hijabi_product_needs_basic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="products.category"
            ),
        ),
    ]
